# Generated by Django 4.1.5 on 2023-02-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.subject', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizes',
            unique_together={('quiz_type', 'subject')},
        ),
    ]
