# Generated by Django 4.1.5 on 2023-02-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_quizes_subject_alter_quizes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scores.subject'),
        ),
    ]
