# Generated by Django 4.1.5 on 2023-02-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_quizes_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizes',
            unique_together={('Total_no', 'subject')},
        ),
    ]
