# Generated by Django 4.1.5 on 2023-02-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_quizes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='Semester',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Sequence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Value_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Value_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz10',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz11',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz12',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz13',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz14',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz15',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz6',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz7',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz8',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='quiz9',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subject',
            name='value',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='OUI', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Lec_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='quizes',
        ),
    ]
