# Generated by Django 4.1.5 on 2023-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_subject_group_subject_semester_subject_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Total_no1',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no10',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no11',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no12',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no13',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no14',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no15',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no2',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no3',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no4',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no5',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no6',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no7',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no8',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Total_no9',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Value_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no11',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no12',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no13',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no14',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no15',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='obt_no9',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='value1',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='OUI', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='value2',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='OUI', max_length=100),
        ),
    ]
