# Generated by Django 4.1.5 on 2023-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_subject_total_no1_subject_total_no10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
