# Generated by Django 4.1.6 on 2023-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='obt_no',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
